apiVersion: v1
kind: Service
metadata:
  name: logdevops-login-backend
  namespace: aut
spec:
  type: NodePort
  selector:
    app: logdevops-login-backend
  ports:
  - port: 9021
    targetPort: 9021
